name: CI/CD

on:
  push:
    branches: [master]

jobs:

  # =========================
  # CI
  # =========================
  build:
    runs-on: ubuntu-latest
    environment: local

    steps:
      - uses: actions/checkout@v4

      # Backend
      - name: Install backend dependencies
        working-directory: ./BE
        run: npm install

      - name: Run backend tests
        working-directory: ./BE
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          PORT: ${{ vars.PORT }}
        run: npm test

      # Frontend
      - name: Install frontend dependencies
        working-directory: ./my-app
        run: npm install

      - name: Build frontend
        working-directory: ./my-app
        env:
          NEXT_PUBLIC_API_URL: ${{ vars.NEXT_PUBLIC_API_URL }}
        run: npm run build


  # =========================
  # CD - DEPLOY TO EC2
  # =========================
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: local

    steps:

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0

        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          PORT: ${{ vars.PORT }}
          NEXT_PUBLIC_API_URL: ${{ vars.NEXT_PUBLIC_API_URL }}

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          envs: MONGO_URI,JWT_SECRET,PORT,NEXT_PUBLIC_API_URL

          script: |
            cd /home/ec2-user/backend/deployment-poc

            echo "Pulling latest code..."
            git pull origin master

            # =========================
            # Backend
            # =========================
            echo "Creating backend environment file..."

            cd BE

            cat > .env <<EOF
            MONGO_URI=$MONGO_URI
            JWT_SECRET=$JWT_SECRET
            PORT=$PORT
            EOF

            echo "Installing backend dependencies..."
            npm install

            echo "Restarting backend..."
            pm2 restart backend --update-env || pm2 start npm --name backend -- start

            # =========================
            # Frontend
            # =========================
            echo "Deploying frontend..."

            cd ../my-app

            npm install

            export NEXT_PUBLIC_API_URL="$NEXT_PUBLIC_API_URL"

            echo "Building frontend..."
            npm run build

            echo "Restarting frontend..."
            pm2 restart frontend --update-env || pm2 start npm --name frontend -- start

            pm2 save

            echo "Deployment completed successfully!"